// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WikiGC.Data;

#nullable disable

namespace WikiGC.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WikiGC.Models.Portais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Responsavel")
                        .HasColumnType("longtext");

                    b.Property<string>("ServidorHomologacao")
                        .HasColumnType("longtext");

                    b.Property<string>("ServidorProducao")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlHomologacao")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlProducao")
                        .HasColumnType("longtext");

                    b.Property<string>("VersaoWordpressHomologacao")
                        .HasColumnType("longtext");

                    b.Property<string>("VersaoWordpressProducao")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Portais");
                });
#pragma warning restore 612, 618
        }
    }
}
